#!/bin/bash

cat << "EOF"
 _______    ______   ______  __    __  ________  __       
|       \  /      \ |      \|  \  |  \|        \|  \      
| $$$$$$$\|  $$$$$$\ \$$$$$$| $$\ | $$| $$$$$$$$| $$      
| $$__/ $$| $$__| $$  | $$  | $$$\| $$| $$__    | $$      
| $$    $$| $$    $$  | $$  | $$$$\ $$| $$  \   | $$      
| $$$$$$$ | $$$$$$$$  | $$  | $$\$$ $$| $$$$$   | $$      
| $$      | $$  | $$ _| $$_ | $$ \$$$$| $$_____ | $$_____ 
| $$      | $$  | $$|   $$ \| $$  \$$$| $$     \| $$     \
 \$$       \$$   \$$ \$$$$$$ \$$   \$$ \$$$$$$$$ \$$$$$$$$
                                                          
                                                          
EOF

echo -e "\033[34m Codado por https/github.com/ddn0x\033[0m\n"

# Verifica se o curl está instalado
if ! [ -x "$(command -v curl)" ]; then
  # Se estivermos no Termux (Android)
  if [ -x "$(command -v pkg)" ]; then
    # Instala o curl com o gerenciador de pacotes do Termux
    pkg install curl
  else
    # Se estivermos em um sistema desktop, tenta instalar o curl com o apt-get (Ubuntu, Debian) ou o yum (Red Hat, CentOS)
    if [ -x "$(command -v apt-get)" ]; then
      apt-get install curl
    elif [ -x "$(command -v yum)" ]; then
      yum install curl
    else
      # Se não soubermos como instalar o curl, exibe uma mensagem de erro
      echo "Não foi possível instalar o curl. Verifique se você tem permissão para instalar pacotes e se está usando um sistema operacional compatível."
      exit 1
    fi
  fi
fi

# Verifica se foi fornecido um URL como argumento
if [ -z "$1" ]; then
  echo -e "\033[31m Nenhum URL fornecido.\033[0m\n"
  echo -e "\033[31m Uso: admin site.com\033[0m\n"
  exit 1
fi


echo -e "\033[31m Por favor aguarde.. \033[0m\n"


# Define o URL base para o site
url=$1

# Define a lista de possíveis caminhos para o painel de administração
paths=(
  "admin.php"
  "admin.html"
  "index.php"
  "login.php"
  "login.html"
  "administrator"
  "admin"
  "adminpanel"
  "cpanel"
  "login"
  "wp-login.php"
  "administrator"
  "admins"
  "logins"
  "admin.asp"
  "login.asp"
  "adm/"
  "admin/"
  "admin/account.html"
  "admin/login.html"
  "admin/login.htm"
  "admin/controlpanel.html"
  "admin/controlpanel.htm"
  "admin/adminLogin.html"
  "admin/adminLogin.htm"
  "admin.htm"
  "admin.html"
  "adminitem/"
  "adminitems/"
  "administrator/"
  "administrator/login.%EXT%"
  "administrator.%EXT%"
  "administration/"
  "administration.%EXT%"
  "adminLogin/"
  "adminlogin.%EXT%"
  "admin_area/admin.%EXT%"
  "admin_area/"
  "admin_area/login.%EXT%"
  "manager/"
  "superuser/"
  "superuser.%EXT%"
  "access/"
  "access.%EXT%"
  "sysadm/"
  "sysadm.%EXT%"
  "superman/"
  "supervisor/"
  "panel.%EXT%"
  "control/"
  "control.%EXT%"
  "member/"
  "member.%EXT%"
  "members/"
  "user/"
  "user.%EXT%"
  "cp/"
  "uvpanel/"
  "manage/"
  "manage.%EXT%"
  "management/"
  "management.%EXT%"
  "signin/"
  "signin.%EXT%"
  "log-in/"
  "log-in.%EXT%"
  "log_in/"
  "log_in.%EXT%"
  "sign_in/"
  "sign_in.%EXT%"
  "sign-in/"
  "sign-in.%EXT%"
  "users/"
  "users.%EXT%"
  "accounts/"
  "accounts.%EXT%"
  "bb-admin/login.%EXT%"
  "bb-admin/admin.%EXT%"
  "bb-admin/admin.html"
  "administrator/account.%EXT%"
  "relogin.htm"
  "relogin.html"
  "check.%EXT%"
  "relogin.%EXT%"
  "blog/wp-login.%EXT%"
  "user/admin.%EXT%"
  "users/admin.%EXT%"
  "registration/"
  "processlogin.%EXT%"
  "checklogin.%EXT%"
  "checkuser.%EXT%"
  "checkadmin.%EXT%"
  "isadmin.%EXT%"
  "authenticate.%EXT%"
  "authentication.%EXT%"
  "auth.%EXT%"
  "authuser.%EXT%"
  "authadmin.%EXT%"
  "cp.%EXT%"
  "modelsearch/login.%EXT%"
  "moderator.%EXT%"
  "moderator/"
  "controlpanel/"
  "controlpanel.%EXT%"
  "admincontrol.%EXT%"
  "adminpanel.%EXT%"
  "fileadmin/"
  "fileadmin.%EXT%"
  "sysadmin.%EXT%"
  "admin1.%EXT%"
  "admin1.html"
  "admin1.htm"
  "admin2.%EXT%"
  "admin2.html"
  "yonetim.%EXT%"
  "yonetim.html"
  "yonetici.%EXT%"
  "yonetici.html"
  "phpmyadmin/"
  "myadmin/"
  "ur-admin.%EXT%"
  "ur-admin/"
  "Server.%EXT%"
  "Server/"
  "wp-admin/"
  "administr8.%EXT%"
  "administr8/"
  "webadmin/"
  "webadmin.%EXT%"
  "administratie/"
  "admins/"
  "admins.%EXT%"
  "administrivia/"
  "Database_Administration/"
  "useradmin/"
  "sysadmins/"
  "admin1/"
  "system-administration/"
  "administrators/"
  "pgadmin/"
  "directadmin/"
  "staradmin/"
  "ServerAdministrator/"
  "SysAdmin/"
  "administer/"
  "LiveUser_Admin/"
  "sys-admin/"
  "typo3/"
  "panel/"
  "cpanel/"
  "cpanel_file/"
  "platz_login/"
  "rcLogin/"
  "blogindex/"
  "formslogin/"
  "autologin/"
  "manuallogin/"
  "simpleLogin/"
  "loginflat/"
  "utility_login/"
  "showlogin/"
  "memlogin/"
  "login-redirect/"
  "sub-login/"
  "wp-login/"
  "login1/"
  "dir-login/"
  "login_db/"
  "xlogin/"
  "smblogin/"
  "customer_login/"
  "UserLogin/"
  "login-us/"
  "acct_login/"
  "bigadmin/"
  "project-admins/"
  "phppgadmin/"
  "pureadmin/"
  "sql-admin/"
  "radmind/"
  "openvpnadmin/"
  "wizmysqladmin/"
  "vadmind/"
  "ezsqliteadmin/"
  "hpwebjetadmin/"
  "newsadmin/"
  "adminpro/"
  "Lotus_Domino_Admin/"
  "bbadmin/"
  "vmailadmin/"
  "Indy_admin/"
  "ccp14admin/"
  "irc-macadmin/"
  "banneradmin/"
  "sshadmin/"
  "phpldapadmin/"
  "macadmin/"
  "administratoraccounts/"
  "admin4_account/"
  "admin4_colon/"
  "radmind-1/"
  "Super-Admin/"
  "AdminTools/"
  "cmsadmin/"
  "SysAdmin2/"
  "globes_admin/"
  "cadmins/"
  "phpSQLiteAdmin/"
  "navSiteAdmin/"
  "server_admin_small/"
  "logo_sysadmin/"
  "power_user/"
  "system_administration/"
  "ss_vms_admin_sm/"
  "bb-admin/"
  "panel-administracion/"
  "instadmin/"
  "memberadmin/"
  "administratorlogin/"
  "adm.%EXT%"
  "admin_login.%EXT%"
  "panel-administracion/login.%EXT%"
  "pages/admin/admin-login.%EXT%"
  "pages/admin/"
  "acceso.%EXT%"
  "admincp/login.%EXT%"
  "admincp/"
  "adminarea/"
  "admincontrol/"
  "affiliate.%EXT%"
  "adm_auth.%EXT%"
  "memberadmin.%EXT%"
  "administratorlogin.%EXT%"
  "modules/admin/"
  "administrators.%EXT%"
  "siteadmin/"
  "siteadmin.%EXT%"
  "adminsite/"
  "kpanel/"
  "vorod/"
  "vorod.%EXT%"
  "vorud/"
  "vorud.%EXT%"
  "adminpanel/"
  "PSUser/"
  "secure/"
  "webmaster/"
  "webmaster.%EXT%"
  "autologin.%EXT%"
  "userlogin.%EXT%"
  "admin_area.%EXT%"
  "cmsadmin.%EXT%"
  "security/"
  "usr/"
  "root/"
  "secret/"
  "admin/login.%EXT%"
  "admin/adminLogin.%EXT%"
  "moderator.php"
  "moderator.html"
  "moderator/login.%EXT%"
  "moderator/admin.%EXT%"
  "yonetici.%EXT%"
  "0admin/"
  "0manager/"
  "aadmin/"
  "cgi-bin/login%EXT%"
  "login1%EXT%"
  "login_admin/"
  "login_admin%EXT%"
  "login_out/"
  "login_out%EXT%"
  "login_user%EXT%"
  "loginerror/"
  "loginok/"
  "loginsave/"
  "loginsuper/"
  "loginsuper%EXT%"
  "login%EXT%"
  "logout/"
  "logout%EXT%"
  "secrets/"
  "super1/"
  "super1%EXT%"
  "super_index%EXT%"
  "super_login%EXT%"
  "supermanager%EXT%"
  "superman%EXT%"
  "superuser%EXT%"
  "supervise/"
  "supervise/Login%EXT%"
  "super%EXT%"
)

# Tenta cada caminho até encontrarmos o painel de administração
for path in "${paths[@]}"; do
  full_url="$url/$path"
  status_code=$(curl -s -o /dev/null -w "%{http_code}" "$full_url")
  if [ "$status_code" == "200" ]; then
    echo -e "\033[32m Painel de administração encontrado em : \033[37m$full_url\033[0m\n"
    exit 0
  fi
done

echo -e "\033[32m Não foi possível encontrar o painel de administração\033[0m\n"
exit 1


